spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/projetoDesenvolvimentoWeb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Garante que dataseeder (se usado) rode DEPOIS do Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true

server.port=8080
